export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';
export const LOGOUT = 'LOGOUT';

// Types of facture
export const ADD_FACTURE_SUCCESS = "ADD_FACTURE_SUCCESS";
export const ADD_FACTURE_FAILED = "ADD_FACTURE_FAILED";
export const GET_FACTURE_SUCCESS = "GET_FACTURE_SUCCESS";
export const GET_FACTURE_FAILED = "GET_FACTURE_FAILED";
export const UPDATE_FACTURE_SUCCESS = "UPDATE_FACTURE_SUCCESS";
export const UPDATE_FACTURE_FAILED = "UPDATE_FACTURE_FAILED";
export const DELETE_FACTURE_SUCCESS = "DELETE_FACTURE_SUCCESS";
export const DELETE_FACTURE_FAILED = "DELETE_FACTURE_FAILED";

// Types of product
export const ADD_PRODUIT_SUCCESS = "ADD_PRODUIT_SUCCESS";
export const ADD_PRODUIT_FAILED = "ADD_PRODUIT_FAILED";
export const GET_PRODUIT_SUCCESS = "GET_PRODUIT_SUCCESS";
export const GET_PRODUIT_FAILED = "GET_PRODUIT_FAILED";
export const UPDATE_PRODUIT_SUCCESS = "UPDATE_PRODUIT_SUCCESS";
export const UPDATE_PRODUIT_FAILED = "UPDATE_PRODUIT_FAILED";
export const DELETE_PRODUIT_SUCCESS = "DELETE_PRODUIT_SUCCESS";
export const DELETE_PRODUIT_FAILED = "DELETE_PRODUIT_FAILED";

