export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';
export const LOGOUT = 'LOGOUT';

// Types of facture
export const ADD_FACTURE_SUCCESS = 'ADD_FACTURE_SUCCESS';
export const ADD_FACTURE_FAILED = 'ADD_FACTURE_FAILED';
export const GET_FACTURE_SUCCESS = 'GET_FACTURE_SUCCESS';
export const GET_FACTURE_FAILED = 'GET_FACTURE_FAILED';
export const UPDATE_FACTURE_SUCCESS = 'UPDATE_FACTURE_SUCCESS';
export const UPDATE_FACTURE_FAILED = 'UPDATE_FACTURE_FAILED';
export const DELETE_FACTURE_SUCCESS = 'DELETE_FACTURE_SUCCESS';
export const DELETE_FACTURE_FAILED = 'DELETE_FACTURE_FAILED';
export const GET_FACTURE_BY_ID_SUCCESS = 'GET_FACTURE_BY_ID_SUCCESS';
export const GET_FACTURE_BY_ID_FAILEDD = 'GET_FACTURE_BY_ID_FAILED';
export const POST_INVOICE_SUCCESS = 'POST_INVOICE_SUCCESS';
export const POST_INVOICE_FAILED = 'POST_INVOICE_FAILED';

// Types of product
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';

// Types of user
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

// counter

export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const RESET = "RESET";

